service: lambda-qna-frontend
frameworkVersion: '3'

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    slim: true
    dockerizePip: true
    useDownloadCache: false
    useStaticCache: false
    fileName: ./requirements/requirements-${env:BRANCH_NAME}.txt

package:
  individually: true
  patterns:
    - '.github/**'
    - '__pycache__/**'
    - 'rough.py'
    - 'sample-questions.json'
    - 'README.md'
  

provider:
  name: aws
  runtime: python3.8
  stage: ${env:MY_ENV}
  region: ${env:MY_REGION}


functions:
  hello:
    handler: handler.send_qna
    maximumRetryAttempts: 2
    memorySize: 512
    environment:
      MY_ENV: ${env:MY_ENV}
      MY_REGION: ${env:MY_REGION}
    events:
      - httpApi:
          path: /qna/{question_id}
          method: get
          parameters:
            paths:
              question_id: true


